<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr\Join;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    /**
     * @param int $max
     *
     * @return array
     */
    public function getFeatured($max = 3)
    {
        return $this->createQueryBuilder('c')
            ->select([
                         'post.id, post.title',
                         'COUNT(c.id) as num_comments',
                     ])
            ->innerJoin('c.post', 'post', Join::WITH)
            ->addGroupBy('post.id')
            ->addGroupBy('post.title')
            ->setMaxResults($max)
            ->getQuery()
            ->getResult()
            ;
    }
}
