# Sonata Admins
services:

    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    AppAdminBundle\Admin\PostAdmin:
        arguments: [~, AppBundle\Entity\Post, ~]
        public: true
        tags:
            - { name: sonata.admin, manager_type: orm, label: "dashboard.content.post_label" }
        calls:
            - { method: 'addChild', arguments: ['@AppAdminBundle\Admin\CommentAdmin'] }

    AppAdminBundle\Admin\CommentAdmin:
            arguments: [~, AppBundle\Entity\Comment, ~]
            public: true
            tags:
                - { name: sonata.admin, manager_type: orm, label: "dashboard.content.comment_label" }

    #Sonata\UserBundle\Admin\Model\UserAdmin:
    #    parent: sonata.user.admin.user
    #    autowire: true
    #    public: true
    #    tags:
    #        - { name: sonata.admin, manager_type: orm, group: "Content", label: "User"}
