# Sonata Block.
sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.user.block.menu: ~
        sonata.user.block.account: ~
        sonata.block.service.text: ~
        sonata.admin.block.admin_list:
            contexts: [admin]
        sonata.admin.block.search_result:
            contexts: [admin]
        sonata.block.service.text: ~
        AppAdminBundle\Block\LatestPostBlock: ~
        AppAdminBundle\Block\FeaturedPostBlock: ~

# Sonata Admin
sonata_admin:
    title: "Carteni's Blog"
    options:
         html5_validate: false
    show_mosaic_button: false
    dashboard:
        blocks:
            -
                position: left
                type: sonata.admin.block.admin_list
            -
                position: right
                type: AppAdminBundle\Block\LatestPostBlock
                settings:
                    title: "Latest Posts"
            -
                position: right
                type: AppAdminBundle\Block\FeaturedPostBlock
                settings:
                    title: "Featured Posts"

    #     groups:
    #         Content:
    #             label: 'Content Management'
    #             items: ~
    #         User:
    #             label: 'User Management'
    #             items:
    #                 - sonata.user.admin.user
                     # - sonata.user.admin.group
    #breadcrumbs:
    #    child_admin_route: edit

# Sonata Media
#
# https://github.com/sonata-project/SonataMediaBundle/issues/707
# https://stackoverflow.com/questions/38568753/sonata-media-bundle-missing-entity-category
# https://github.com/sonata-project/SonataMediaBundle/issues/862#issuecomment-163956345
#
# Execute:
# bin/console sonata:classification:fix-context
# bin/console sonata:media:fix-media-context
sonata_media:
    providers:
        image:
            resizer: sonata.media.resizer.square

    db_driver: doctrine_orm # or doctrine_mongodb, doctrine_phpcr it is mandatory to choose one here

    default_context: media # you need to set a context

    class:
        media: Application\Sonata\MediaBundle\Entity\Media
        gallery: Application\Sonata\MediaBundle\Entity\Gallery
        gallery_has_media: Application\Sonata\MediaBundle\Entity\GalleryHasMedia
        category: Application\Sonata\ClassificationBundle\Entity\Category

    contexts:
        default:  # the default context is mandatory
            providers:
                - sonata.media.provider.image
                - sonata.media.provider.file
            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}
        media:
            providers:
                - sonata.media.provider.image
                - sonata.media.provider.image
            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}

    cdn:
        server:
            path: /uploads/media

    filesystem:
        local:
            directory:  "%kernel.root_dir%/../web/uploads/media"
            create:     false

# Sonata Classification
sonata_classification:
    admin:
        category:
            class: Application\Sonata\ClassificationBundle\Admin\CategoryAdmin

# Sonata User
sonata_user:
    admin:
        user:
            class: Application\Sonata\UserBundle\Admin\UserAdmin
        group:
            class: Application\Sonata\UserBundle\Admin\GroupAdmin

# FOS User
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Application\Sonata\UserBundle\Entity\User
    group:
        group_class: Application\Sonata\UserBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager
    service:
        user_manager: sonata.user.orm.user_manager
    from_email:
        address: webmaster@carteni.blog
        sender_name: Admin
