# SonataBlock configs.
sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.user.block.menu: ~
        sonata.user.block.account: ~
        sonata.block.service.text: ~
        sonata.admin.block.admin_list:
            contexts: [admin]
        sonata.admin.block.search_result:
            contexts: [admin]

# FOSUser configs.
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Application\Sonata\UserBundle\Entity\User
    group:
        group_class: Application\Sonata\UserBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager
    service:
        user_manager: sonata.user.orm.user_manager
    from_email:
        address: webmaster@carteni.blog
        sender_name: Admin

# Sonata Admin
sonata_admin:
    title: "Carteni's Blog"
    options:
         html5_validate: false
    show_mosaic_button: false
    dashboard:
         groups:
             Content:
                 label: 'Content Management'
                 items: ~
             User:
                 label: 'User Management'
                 items:
                     - sonata.user.admin.user
                     # - sonata.user.admin.group
    breadcrumbs:
        child_admin_route: edit