# Sonata Block.
sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.user.block.menu: ~
        sonata.user.block.account: ~
        sonata.block.service.text: ~
        sonata.admin.block.admin_list:
            contexts: [admin]
        sonata.admin.block.search_result:
            contexts: [admin]
        sonata.block.service.text: ~
        AppAdminBundle\Block\LatestPostBlock: ~
        AppAdminBundle\Block\FeaturedPostBlock: ~

# Sonata Admin
sonata_admin:
    title: "Carteni's Blog"
    templates:
        layout: AppAdminBundle::standard_layout.html.twig
        #edit: AppAdminBundle:CRUD:edit.html.twig
    options:
         html5_validate: false
    show_mosaic_button: false
    dashboard:
        blocks:
            -
                position: left
                type: sonata.admin.block.admin_list
            -
                position: right
                type: AppAdminBundle\Block\LatestPostBlock
                settings:
                    title: block.latest_posts
            -
                position: right
                type: AppAdminBundle\Block\FeaturedPostBlock
                settings:
                    title: block.featured_posts

        groups:
            Content:
                label: 'dashboard.content.group.content_label'
                items:
                    - AppAdminBundle\Admin\PostAdmin
                    - AppAdminBundle\Admin\CommentAdmin
                    - sonata.classification.admin.context
                    - sonata.classification.admin.category
                    - sonata.media.admin.media
            User:
                label: 'dashboard.content.group.user_label'
                icon: '<i class="fa fa-user"></i>'
                items:
                    - sonata.user.admin.user
                    - sonata.user.admin.group
            my_group:
                    provider: custom_menu # alias defined in services.yml
                    icon: '<i class="fa fa-edit"></i>'
    #breadcrumbs:
    #    child_admin_route: edit

# Sonata Media
#
# https://github.com/sonata-project/SonataMediaBundle/issues/707
# https://stackoverflow.com/questions/38568753/sonata-media-bundle-missing-entity-category
# https://github.com/sonata-project/SonataMediaBundle/issues/862#issuecomment-163956345
#
# Execute:
# bin/console sonata:classification:fix-context
# bin/console sonata:media:fix-media-context
sonata_media:
    providers:
        image:
            resizer: sonata.media.resizer.square

    db_driver: doctrine_orm # or doctrine_mongodb, doctrine_phpcr it is mandatory to choose one here

    default_context: media # you need to set a context

    class:
        media: Application\Sonata\MediaBundle\Entity\Media
        gallery: Application\Sonata\MediaBundle\Entity\Gallery
        gallery_has_media: Application\Sonata\MediaBundle\Entity\GalleryHasMedia
        category: Application\Sonata\ClassificationBundle\Entity\Category

    contexts:
        default:  # the default context is mandatory
            providers:
                - sonata.media.provider.image
                - sonata.media.provider.file
            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}
        media:
            providers:
                - sonata.media.provider.image
                - sonata.media.provider.file
            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}
        upload:
            providers:
                - sonata.media.provider.image
                - sonata.media.provider.file
            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}
    cdn:
        server:
            path: /uploads/media

    filesystem:
        local:
            directory:  "%kernel.root_dir%/../web/uploads/media"
            create:     false

# Sonata Classification
sonata_classification:
    admin:
        category:
            class: Application\Sonata\ClassificationBundle\Admin\CategoryAdmin

# Sonata User
sonata_user:
    admin:
        user:
            class: Application\Sonata\UserBundle\Admin\UserAdmin
        group:
            class: Application\Sonata\UserBundle\Admin\GroupAdmin

# FOS User
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Application\Sonata\UserBundle\Entity\User
    group:
        group_class: Application\Sonata\UserBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager
    service:
        user_manager: sonata.user.orm.user_manager
    from_email:
        address: webmaster@carteni.blog
        sender_name: Admin


# Sonata Formatter
#sonata_formatter:
#    default_formatter: richhtml
#    formatters:
#        richhtml:
#            service: sonata.formatter.text.raw
#            extensions:
#                - sonata.formatter.twig.control_flow
#                - sonata.formatter.twig.gist
#                - sonata.media.formatter.twig
#        twig:
#            service: sonata.formatter.text.twigengine
#            extensions: [] # Twig formatter cannot have extensions

# IvoryCKEditorBundle
ivory_ck_editor:
    jquery: true
    autoload: true
    async: false
    default_config: default
    configs:
        # https://github.com/egeloen/IvoryCKEditorBundle/issues/194
        default:
            filebrowserBrowseRoute: admin_sonata_media_media_browser
            filebrowserImageBrowseRoute: admin_sonata_media_media_browser
            # Display images by default when clicking the image dialog browse button
            filebrowserImageBrowseRouteParameters:
                provider: sonata.media.provider.image
            filebrowserUploadRoute: admin_sonata_media_media_upload
            filebrowserUploadRouteParameters:
                provider: sonata.media.provider.file
                context: uplodad # from "link" button

            # Upload file as image when sending a file from the image dialog
            filebrowserImageUploadRoute: admin_sonata_media_media_upload
            filebrowserImageUploadRouteParameters:
                provider: sonata.media.provider.image
                context: upload # Optional, to upload in a custom context (from "image" button)
                # other parameters...
            toolbar:
                - [Bold, Italic, Underline, -, NumberedList, BulletedList, -, Outdent, Indent, -, Blockquote, -, Image, Link, Unlink]
                - [Templates, Format, Styles]
                - [Maximize, Source]
            format_tags: 'p;h1;h2;h3;h4;div'
            language: '%locale%'
            allowedContent: true
            #contentCss: "app.css"
            uiColor: "#FFFFFF"

coop_tilleuls_ck_editor_sonata_media:
    templates:
        layout: ApplicationSonataMediaBundle:MediaAdmin:layout.html.twig # Layout of the file browser
        browser: ApplicationSonataMediaBundle:MediaAdmin:browser.html.twig # Template of the CKEditor file browser
        upload: ApplicationSonataMediaBundle:MediaAdmin:upload.html.twig # Template returned after a direct upload

sonata_doctrine_orm_admin:
    templates:
        form:
            - AppAdminBundle:Form:form_admin_fields.html.twig
