services:

    _defaults:
        public: false
        autowire: true
        autoconfigure: true


    AppAdminBundle\EventListener\PostEventSubscriber:
        tags:
            - { name: doctrine.event_subscriber, connection: default}

    AppAdminBundle\EventListener\CommentEventSubscriber:
        tags:
            - { name: doctrine.event_subscriber, connection: default}

    Cocur\Slugify\Slugify: ~

    Cocur\Slugify\SlugifyInterface: '@Cocur\Slugify\Slugify'

    # Blocks
    AppAdminBundle\Block\LatestPostBlock:
        public: true
        autowire: false
        arguments: ['Latest Posts', '@templating', "@=service('doctrine.orm.entity_manager').getRepository('AppBundle:Post')"]
        tags:
            - { name: sonata.block }

    AppAdminBundle\Block\FeaturedPostBlock:
        public: true
        autowire: false
        arguments: ['Latest Posts', '@templating', "@=service('doctrine.orm.entity_manager').getRepository('AppBundle:Comment')"]
        tags:
            - { name: sonata.block }
